feat: add external-secrets to the bootstrapper
open-component-model/MPAS pull request #112
Opened 2023-10-19 14:42 UTC by Skarlso

## Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

- Related Issue # (issue)
- Closes # (issue)
- Fixes # (issue)
> Remove if not applicable

## Screenshots

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help
- [ ] Separate ticket for tests # (issue/pr)

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Added e2e-tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help
- [ ] Separate ticket for e2e-tests

## Added to documentation?

- [ ] 📜 README.md
- [ ] 🙅 no documentation needed

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-10-19 16:08 UTC, Skarlso commented
So far so good:

```
Release of bootstrap component successful.
```

2023-10-20 08:32 UTC, Skarlso commented
Works now!

```
Image:         ghcr.io/skarlso/mpas-bootstrap-external-secrets/external-secrets/external-secrets:v0.9.6
```

2023-10-20 09:27 UTC, Skarlso commented
Closes #112

2023-10-20 10:20 UTC, Skarlso commented
```
/bin/mpas bootstrap github --owner skarlso --repository=mpas-test-project --personal --registry ghcr.io/skarlso/mpas-bootstrap-external-secrets
Running mpas bootstrap ...
 ✓   Preparing Management repository mpas-test-project
 ✓   Fetching bootstrap component from ghcr.io/skarlso/mpas-bootstrap-external-secrets
 ✓   Installing flux with version v2.1.0
 ✓   Installing cert-manager with version v1.13.1
 ✓   Installing external-secrets-operator with version v0.9.6
 ✓   Reconciling infrastructure components
 ✓   Waiting for cert-manager to be available
 ✓   Waiting for external-secrets to be available
 ✓   Generating git-controller manifest with version v0.8.0
 ✓   Generating mpas-product-controller manifest with version v0.5.1
 ✓   Generating mpas-project-controller manifest with version v0.3.1
 ✓   Generating ocm-controller manifest with version v0.14.0
 ✓   Generating replication-controller manifest with version v0.8.0
 ✓   Generate certificate manifests
 ✓   Reconciling infrastructure components
 ✓   Waiting for components to be ready

Bootstrap completed successfully!

```

2023-10-20 11:24 UTC, Skarlso commented
Needs https://github.com/open-component-model/git-controller/pull/73 to use the local `http://gitea` instance.

2023-10-20 11:41 UTC, Skarlso commented
And this https://github.com/open-component-model/mpas-project-controller/pull/46

2023-10-20 11:45 UTC, phoban01 reviewed
Would the logic be a bit easier here if we made everything positive and default the flag to true?

2023-10-20 11:57 UTC, Skarlso commented
@phoban01 where what which? 🤣 the disable of the component? Actually I found a better way to do that. I'll just leave out of the list of components instead of having that huge if there. That will be a bit nicer. Or are you referring to something else?

2023-10-20 14:23 UTC, Skarlso commented
```
PASS
ok      github.com/open-component-model/mpas/e2e        326.154s

DONE 40 tests in 343.800s

```

E2E tests after using the latest project and git controller.

2023-10-24 12:34 UTC, Skarlso commented
With the switch:

```
✗ ./bin/mpas bootstrap github --owner skarlso --repository=mpas-test-project --personal --registry ghcr.io/skarlso/mpas-bootstrap-external-secrets --disable-external-secret-component
Running mpas bootstrap ...
 ✓   Preparing Management repository mpas-test-project
 ✓   Fetching bootstrap component from ghcr.io/skarlso/mpas-bootstrap-external-secrets
 ✓   Installing flux with version v2.1.0
 ✓   Installing cert-manager with version v1.13.1
 ✓   Reconciling infrastructure components
 ✓   Waiting for cert-manager to be available
 ✓   Generating git-controller manifest with version v0.8.0
 ✓   Generating mpas-product-controller manifest with version v0.5.1
 ✓   Generating mpas-project-controller manifest with version v0.3.1
 ✓   Generating ocm-controller manifest with version v0.14.0
 ✓   Generating replication-controller manifest with version v0.8.0
 ✓   Generate certificate manifests
 ✓   Reconciling infrastructure components
 ✓   Waiting for components to be ready

Bootstrap completed successfully!

```

2023-10-24 16:09 UTC, souleb requested changes

2023-10-24 17:14 UTC, Skarlso commented on cmd/mpas/bootstrap.go
> +				DisableExternalSecretComponent: c.DisableExternalSecretComponent,
Sure we can but the installation doesn't follow that. Infact it will error if the component is in the list but not enabled or in the list of components to install.

I can rewrite the whole thing to use that strategy instead I guess.

2023-10-24 18:51 UTC, Skarlso commented on cmd/mpas/bootstrap.go
> +				DisableExternalSecretComponent: c.DisableExternalSecretComponent,
For example, right now, if you leave out flux from the list of components to install it will plain error. Or if you leave out cert-manager it will still try to get its health.

This is not the case of external secrets manager as we don't want to check for health of it if its left out.

BTW, I'm already doing this:

```go
	if b.disableExternalSecretsComponent {
		delete(refs, env.ExternalSecretsName)
	}
```

So technically it's already left out of the list of components if it's not enabled.

2023-10-24 18:54 UTC, Skarlso commented on cmd/mpas/bootstrap.go
> +				DisableExternalSecretComponent: c.DisableExternalSecretComponent,
Also, the problem with that list is that to disable a single item, you have to define ALL of the items that do need to be installed.

So what do you think of instead giving an `exclude` list or something?

2023-10-24 23:23 UTC, souleb commented on cmd/mpas/bootstrap.go
> +				DisableExternalSecretComponent: c.DisableExternalSecretComponent,
```go
append(env.Components, c.Components...), 
```

It means that `c.Components` are extra components. Once you add them they are part of the components that have to be installed and healtchecked. I believe we can do that as we loop over the component list are check their `deployments` statuses. `Flux` and other `OCM` are different as they are required and must be part of `env.Components`. 

I believe that it's better with an extra components list, to make sure that we install only the required components by default, and users have to opt-in for anything extra.

2023-10-25 04:32 UTC, Skarlso commented on cmd/mpas/bootstrap.go
> +				DisableExternalSecretComponent: c.DisableExternalSecretComponent,
Ah I see what you mean. So how would you disable that? --extra-components="" ?

2023-10-25 08:57 UTC, Skarlso commented on cmd/mpas/bootstrap.go
> +				DisableExternalSecretComponent: c.DisableExternalSecretComponent,
Oaky, yah that could work nicely, you're right. I just add `external-secrets` by default to the extend the component handler switch instead of doing what I do now. 

Good suggestion 👍

2023-10-25 09:10 UTC, Skarlso commented on cmd/mpas/bootstrap.go
> +				DisableExternalSecretComponent: c.DisableExternalSecretComponent,
Okay, so it is a _bit_ difficult since neither the components nor the deployment strategy matches with our components. So I do need some kind of custom health check that is more akin to the cert-manager... Which is why this was its own component. But I'll manage something.

2023-10-25 09:22 UTC, Skarlso commented
Works with the new suggestion from Soule:

```
./bin/mpas bootstrap github --owner skarlso --repository=mpas-test-project --personal --registry ghcr.io/skarlso/mpas-bootstrap-external-secrets
Running mpas bootstrap ...
 ✓   Preparing Management repository mpas-test-project
 ✓   Fetching bootstrap component from ghcr.io/skarlso/mpas-bootstrap-external-secrets
 ✓   Installing flux with version v2.1.0
 ✓   Installing cert-manager with version v1.13.1
 ✓   Reconciling infrastructure components
 ✓   Waiting for cert-manager to be available
 ✓   Generating external-secrets-operator manifest with version v0.9.6
 ✓   Generating git-controller manifest with version v0.8.0
 ✓   Generating mpas-product-controller manifest with version v0.5.1
 ✓   Generating mpas-project-controller manifest with version v0.3.1
 ✓   Generating ocm-controller manifest with version v0.14.0
 ✓   Generating replication-controller manifest with version v0.8.0
 ✓   Generate certificate manifests
 ✓   Reconciling infrastructure components
 ✓   Waiting for components to be ready

Bootstrap completed successfully!

```

```
k get pods -A
NAMESPACE            NAME                                                READY   STATUS    RESTARTS   AGE
cert-manager         cert-manager-5c698fd7-gtjf7                         1/1     Running   0          2m19s
cert-manager         cert-manager-cainjector-dbc6bddff-xxs9w             1/1     Running   0          2m19s
cert-manager         cert-manager-webhook-5644bc9cf9-trrd8               1/1     Running   0          2m19s
default              external-secrets-59ddc788cd-j5lg6                   1/1     Running   0          96s
default              external-secrets-cert-controller-78f6d694cb-8hl8g   1/1     Running   0          96s
default              external-secrets-webhook-6c8c667647-kzhwm           1/1     Running   0          96s
flux-system          helm-controller-7d5b45865d-r6rmk                    1/1     Running   0          2m58s
flux-system          image-automation-controller-7549fcbf6f-p2nq8        1/1     Running   0          2m58s
flux-system          image-reflector-controller-6b9b5d444-xcbz8          1/1     Running   0          2m58s
flux-system          kustomize-controller-854b649f79-bn9vm               1/1     Running   0          2m58s
flux-system          notification-controller-6988665c99-2jtjp            1/1     Running   0          2m58s
flux-system          source-controller-79c4b99987-89mg4                  1/1     Running   0          2m58s
kube-system          coredns-5d78c9869d-bl5jt                            1/1     Running   0          9m41s
kube-system          coredns-5d78c9869d-hbzcg                            1/1     Running   0          9m41s
kube-system          etcd-ocm-test-control-plane                         1/1     Running   0          9m54s
kube-system          kindnet-jqxrf                                       1/1     Running   0          9m41s
kube-system          kube-apiserver-ocm-test-control-plane               1/1     Running   0          9m54s
kube-system          kube-controller-manager-ocm-test-control-plane      1/1     Running   0          9m54s
kube-system          kube-proxy-jkzvr                                    1/1     Running   0          9m41s
kube-system          kube-scheduler-ocm-test-control-plane               1/1     Running   0          9m54s
local-path-storage   local-path-provisioner-6bc4bddd6b-55rdn             1/1     Running   0          9m41s
mpas-system          mpas-product-controller-76fb65dfcc-vk4vl            1/1     Running   0          96s
mpas-system          mpas-project-controller-f64bd64cd-77v9k             1/1     Running   0          96s
ocm-system           git-controller-7f85df6857-9hwdv                     1/1     Running   0          96s
ocm-system           ocm-controller-7bfb75f946-9c6g4                     1/1     Running   0          96s
ocm-system           registry-8667fbb848-sgcdb                           1/1     Running   0          95s
ocm-system           replication-controller-675cbf8cb8-p5q6h             1/1     Running   0          95s

```

2023-10-25 09:22 UTC, Skarlso commented
Now, trying to do one without the external-secrets component:

2023-10-25 11:11 UTC, phoban01 approved these changes

2023-10-25 13:46 UTC, souleb approved these changes
LGTM! Thanks @Skarlso

2023-10-25 13:46 UTC, souleb commented on cmd/mpas/config/config.go
> +	flags.StringSliceVar(&m.Components, "components", []string{env.ExternalSecretsName}, "The components to include in the management repository")
lol that's a smart way to do that!

2023-10-25 14:38 UTC, merged